from __future__ import annotations

from itertools import permutations, product

import numpy as np
import pytest

from fast_math import (
    tuple_orbit_canonicalize,
    tuple_orbit_partition,
    tuple_orbit_space,
)
from fast_math._native import (
    tuple_orbit_canonicalize_native,
    tuple_orbit_space_native,
)

BACKENDS = ["reference", "native"]


def encode(tup, base):
    code = 0
    for digit in tup:
        code = code * base + digit
    return code


def brute_orbit(seed, generators, base, width):
    """Hand-written fleet pattern: closure by BFS over generator images."""
    seed_digits = [(seed // base**i) % base for i in range(width)][::-1]

    def image(permutation, digits):
        out = [0] * width
        for i, target in enumerate(permutation):
            out[target] = digits[i]
        return out

    orbit = {tuple(seed_digits)}
    queue = [tuple(seed_digits)]
    while queue:
        current = queue.pop()
        for generator in generators:
            image_tuple = tuple(
                image(tuple(int(v) for v in generator), list(current))
            )
            if image_tuple not in orbit:
                orbit.add(image_tuple)
                queue.append(image_tuple)
    return {encode(digits, base) for digits in orbit}


def cyclic_shift(width):
    return np.roll(np.arange(width), -1).astype(np.uint32)


@pytest.mark.parametrize("backend", BACKENDS)
def test_binary_necklaces_width_five(backend: str) -> None:
    # Cyclic C5 acting on Z_2^5: 8 binary necklaces of length five.
    generators = [cyclic_shift(5)]
    space = tuple_orbit_space(generators, 2, 5, backend=backend)
    assert space.orbit_count == 8
    assert space.group_size == 5
    assert space.burnside_orbit_count == 8
    assert space.burnside_valid
    assert len(space.orbit_ids) == 32
    # Necklaces: constant 0s, 1s, and weight classes acted on by C5.
    assert list(space.representatives) == sorted(space.representatives)


@pytest.mark.parametrize("backend", BACKENDS)
def test_full_symmetric_group_gives_multisets(backend: str) -> None:
    # S4 generated by adjacent transpositions acts on Z_3^4; orbits are the
    # multisets of digits, counted by C(4 + 3 - 1, 4) = 15.
    generators = np.array(
        [
            [1, 0, 2, 3],
            [0, 2, 1, 3],
            [0, 1, 3, 2],
        ],
        dtype=np.uint32,
    )
    space = tuple_orbit_space(generators, 3, 4, backend=backend)
    assert space.group_size == 24
    assert space.orbit_count == 15
    assert space.burnside_orbit_count == 15
    assert space.burnside_valid


@pytest.mark.parametrize("backend", BACKENDS)
def test_canonicalize_matches_min_orbit_image(backend: str) -> None:
    width, base = 5, 3
    generators = np.array(
        [cyclic_shift(width), list(range(width - 1, -1, -1))],
        dtype=np.uint32,
    )  # dihedral D5
    rng = np.random.default_rng(11)
    codes = rng.integers(0, base**width, size=257, dtype=np.uint64)
    canonical, is_canonical = tuple_orbit_canonicalize(
        generators, base, width, codes, backend=backend
    )
    gen_list = [np.array(row) for row in generators]
    for code, can, flag in zip(codes, canonical, is_canonical):
        orbit = brute_orbit(int(code), gen_list, base, width)
        assert int(can) == min(orbit)
        assert bool(flag) == (int(code) == int(can))


@pytest.mark.parametrize("backend", BACKENDS)
def test_partition_matches_brute_orbit_classes(backend: str) -> None:
    width, base = 4, 2
    generators = np.array([cyclic_shift(width)], dtype=np.uint32)
    rng = np.random.default_rng(23)
    codes = rng.integers(0, base**width, size=101, dtype=np.uint64)
    partition = tuple_orbit_partition(
        generators, base, width, codes, backend=backend
    )
    np.testing.assert_array_equal(
        partition.representatives,
        np.unique(partition.canonical_codes),
    )
    gen_list = [np.array(row) for row in generators]
    for code, class_id in zip(codes, partition.class_ids):
        orbit = brute_orbit(int(code), gen_list, base, width)
        assert partition.representatives[class_id] == min(orbit)
    np.testing.assert_array_equal(
        partition.class_sizes,
        np.bincount(partition.class_ids).astype(np.uint64),
    )
    np.testing.assert_array_equal(
        partition.class_ids,
        np.searchsorted(
            partition.representatives, partition.canonical_codes
        ),
    )


@pytest.mark.parametrize("backend", BACKENDS)
def test_space_ids_agree_with_partition(backend: str) -> None:
    width, base = 6, 2
    generators = np.array(
        [cyclic_shift(width), [0, 2, 1, 3, 4, 5]], dtype=np.uint32
    )
    space = tuple_orbit_space(generators, base, width, backend=backend)
    canonical, _ = tuple_orbit_canonicalize(
        generators,
        base,
        width,
        np.arange(base**width, dtype=np.uint64),
        backend=backend,
    )
    np.testing.assert_array_equal(
        space.representatives[space.orbit_ids], canonical
    )


def test_all_generators_one_swap_closure(backend: str = "native") -> None:
    # S3 from one transposition and identity-free closure must include all
    # three group elements generated... a single transposition generates C2.
    generators = np.array([[1, 0, 2]], dtype=np.uint32)
    _, stats = tuple_orbit_space_native(generators, 3, 3, 3**3)
    assert stats.group_size == 2


def test_native_stats_and_flags() -> None:
    width, base = 4, 2
    generators = np.array([cyclic_shift(width)], dtype=np.uint32)
    codes = np.array([0, 1, 2, 3, 15], dtype=np.uint64)
    canonical, flags, stats = tuple_orbit_canonicalize_native(
        generators, width, base, codes
    )
    assert stats.group_size == 4
    assert stats.code_count == 5
    # 1, 2 rotate; 0, 3 (0011 = min of its orbit 3,6,9,12), 15 fixed.
    np.testing.assert_array_equal(
        canonical, np.array([0, 1, 1, 3, 15], dtype=np.uint64)
    )
    assert flags.tolist() == [True, True, False, True, True]
    _, space_stats = tuple_orbit_space_native(
        generators, width, base, base**width
    )
    assert space_stats.burnside_valid
    assert space_stats.orbit_count == space_stats.burnside_orbit_count


def test_rejects_invalid_inputs() -> None:
    good = np.array([cyclic_shift(4)], dtype=np.uint32)
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(good, 1, 4, [0])  # base too small
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(good, 2, 0, [0])  # width zero
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(
            np.empty((0, 4), dtype=np.uint32), 2, 4, [0]
        )  # no generators
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(
            np.array([[0, 0, 2, 3]], dtype=np.uint32), 2, 4, [0]
        )  # not a permutation
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(good, 2, 4, [16])  # code outside range
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(good, 2, 4, [-1])
    with pytest.raises(ValueError):
        tuple_orbit_canonicalize(
            np.array([[0, 1, 2]], dtype=np.uint32), 2, 4, [0]
        )  # wrong width
    with pytest.raises(ValueError):
        tuple_orbit_space(good, 2, 25)  # 2**25 exceeds the space cap


def test_identity_group_orbits_are_singletons() -> None:
    generators = np.arange(4, dtype=np.uint32).reshape(1, 4)
    space = tuple_orbit_space(generators, 2, 4)
    assert space.group_size == 1
    assert space.orbit_count == 16
    np.testing.assert_array_equal(
        space.orbit_ids, np.arange(16, dtype=np.uint64)
    )
