"""High-throughput native kernels shared across mathematical research.

``fast_math.find("csr")`` from Python, ``fast-math --find csr`` from a shell:
both answer "is the kernel I am about to write by hand already here".
"""

from .index import Entry, entries, find
from .cnf import CnfBackend, CnfEvaluation, CnfPlan, pack_boolean_assignments
from .modular import (
    ModularBackend,
    ModularDeterminantBatch,
    ModularDeterminantPlan,
    ModularPolynomialEvaluation,
    ModularPolynomialPlan,
    determinants_mod_u32,
)
from .modular_linear import ModularLinearSystemPlan, ModularSolveBatch
from .runtime import BackendCapability, backend_capabilities
from .actions import (
    ActionBackend,
    CanonicalMaskBatch,
    MaskOrbitPartition,
    PermutationActionPlan,
    compose_u64_mask_luts,
    u64_mask_lut,
)
from .plans import CayleyGraphPlan, FiniteGroupPlan, GraphCanonicalPlan
from .segments import SegmentedComplexStats, segmented_complex_stats
from .graph64 import (
    CliqueBatchResult,
    DecodedGraphBatch,
    EncodedGraphBatch,
    GraphInvariantBatch,
    GraphPairProfiles,
    InducedProfileBatch,
    InducedProfileStackBatch,
    RootedLeafFeatureBatch,
    VertexDeletedGraphBatch,
    decode_graph6,
    delete_graph_vertices,
    encode_graph6,
    find_cliques,
    find_independent_sets,
    graph_invariants,
    graph_pair_profiles,
    induced_subgraph_profiles,
    induced_subgraph_profile_stack,
    rooted_leaf_attachment_features,
)
from .taylor import (
    TaylorCoefficientResult,
    TaylorEvaluationResult,
    evaluate_taylor_basis,
    taylor_coefficients,
)
from .finufft import (
    FinufftUnavailable,
    PlanTimings,
    Type1Plan1D,
    Type3FixedPlan1D,
    Type3Plan1D,
    Type3SignPairPlan1D,
)
from .filon import (
    FilonInnerProductResult,
    chebyshev_lobatto_endpoint_derivatives,
    filon_chebyshev_inner_product,
)
from .affine import (
    AffineBackend,
    AffineContourMetrics,
    AffineNumpyPlan,
    affine_plan,
)
from .metal import (
    AffineMetalPlan,
    MetalUnavailable,
)
from .cuda import (
    AffineCudaPlan,
    CudaUnavailable,
)
from .hip import (
    AffineHipPlan,
    HipUnavailable,
    SquareCoverHipPlan,
    SubsetActionHipPlan,
    hip_available,
    hip_cnf_available,
    hip_modular_available,
    hip_modular_linear_available,
    hip_subset_actions_available,
)
from .large_graph import (
    CommonNeighborBatch,
    TriangleBatch,
    UndirectedCSR,
    csr_common_neighbors,
    enumerate_csr_triangles,
    undirected_csr,
)
from .canonical import (
    CanonicalDigraphBatch,
    canonicalize_colored_digraphs,
    pack_digraph_adjacency,
)
from .digest import (
    UInt64DigestBatch,
    digest_u64_rows,
    serialize_u64_row,
)
from .sparse import (
    SparseBlockColoopResult,
    SparseRankBatchResult,
    SparseRankResult,
    sparse_block_coloops_mod_u32,
    sparse_rank_mod_u32,
    sparse_rank_mod_u32_batch,
)
from .elliptic import (
    MestreApTables,
    QuarticFibre,
    mestre_ap_tables,
    mestre_locus_residual,
    mestre_quartic,
    quartic_points,
)
from .union import union_closed_family_masks
from .adaptive import (
    AdaptiveAreaBatch,
    AdaptiveBackend,
    ExactAdaptiveAreaBatch,
    adaptive_areas,
    exact_adaptive_areas,
    quadratic_target_tables,
    restriction_assignment,
    restriction_code,
    restriction_count,
)
from .packing import (
    PackingBackend,
    SquareCoverBatch,
    SquareScoreBatch,
    oriented_square_cover_words,
    oriented_square_weighted_scores,
)
from .groups import (
    DoubleCosetPartition,
    GroupBackend,
    PermutationGroup,
    SchreierSimsChain,
    compose_permutations,
    group_order,
    invert_permutation,
    permutation_double_cosets,
    permutation_group_contains,
    permutation_orbits,
    schreier_sims,
)
from .ci import (
    CIBackend,
    CanonicalCayleyBatch,
    CayleyGraphBatch,
    CoherentConfiguration,
    DerivativeOrbitBatch,
    DerivativeOrbitPartition,
    FixedWeightSubsetOrbits,
    GeneralizedDihedralGroup,
    InverseClosedAtoms,
    SubsetOrbitPartition,
    WL2Refinement,
    atom_subsets_to_element_words,
    canonicalize_cayley_graphs,
    cayley_graphs,
    coherent_configuration,
    deduplicate_subset_orbits,
    derivative_group_orbits,
    derivative_orbit_partitions,
    double_cosets,
    enumerate_fixed_weight_subset_orbits,
    enumerate_subset_orbits,
    expand_atom_masks,
    generalized_dihedral_automorphisms,
    generalized_dihedral_group,
    graph_coherent_configuration,
    graph_wl2_refinement,
    induced_atom_action,
    induced_atom_generators,
    inverse_closed_atoms,
    pack_subsets,
    wl2_refinement,
)

_LAMBDA_EXPORTS = {
    "AccumulationResult",
    "InverseResult",
    "PairCounts",
    "PowerMoment",
    "PowerMomentResult",
    "TwoLevelRecord",
    "TwoLevelResult",
    "accumulate_coefficients",
    "available_backends",
    "dirichlet_inverse",
    "fused_two_level",
    "native_version",
    "power_moments",
    "truncated_inverse",
}


def __getattr__(name: str):
    if name not in _LAMBDA_EXPORTS:
        raise AttributeError(f"module 'fast_math' has no attribute {name!r}")
    import lambda_fast

    value = getattr(lambda_fast, name)
    globals()[name] = value
    return value


__all__ = [
    "Entry",
    "entries",
    "find",
    "AccumulationResult",
    "ActionBackend",
    "AffineBackend",
    "AffineContourMetrics",
    "AffineCudaPlan",
    "AffineMetalPlan",
    "AffineNumpyPlan",
    "AffineHipPlan",
    "BackendCapability",
    "CanonicalMaskBatch",
    "CayleyGraphPlan",
    "CnfBackend",
    "CnfEvaluation",
    "CnfPlan",
    "CliqueBatchResult",
    "CommonNeighborBatch",
    "CudaUnavailable",
    "HipUnavailable",
    "CanonicalDigraphBatch",
    "DecodedGraphBatch",
    "EncodedGraphBatch",
    "GraphInvariantBatch",
    "GraphPairProfiles",
    "GraphCanonicalPlan",
    "FiniteGroupPlan",
    "InducedProfileBatch",
    "InducedProfileStackBatch",
    "InverseResult",
    "FinufftUnavailable",
    "FilonInnerProductResult",
    "MaskOrbitPartition",
    "MetalUnavailable",
    "ModularBackend",
    "ModularDeterminantBatch",
    "ModularDeterminantPlan",
    "ModularLinearSystemPlan",
    "ModularPolynomialEvaluation",
    "ModularPolynomialPlan",
    "ModularSolveBatch",
    "PairCounts",
    "PermutationActionPlan",
    "PackingBackend",
    "PlanTimings",
    "PowerMoment",
    "PowerMomentResult",
    "RootedLeafFeatureBatch",
    "SegmentedComplexStats",
    "SparseBlockColoopResult",
    "SparseRankResult",
    "SparseRankBatchResult",
    "SquareCoverBatch",
    "SquareCoverHipPlan",
    "SquareScoreBatch",
    "SubsetActionHipPlan",
    "TaylorCoefficientResult",
    "TaylorEvaluationResult",
    "TriangleBatch",
    "TwoLevelRecord",
    "TwoLevelResult",
    "Type1Plan1D",
    "Type3FixedPlan1D",
    "Type3Plan1D",
    "Type3SignPairPlan1D",
    "UInt64DigestBatch",
    "UndirectedCSR",
    "VertexDeletedGraphBatch",
    "accumulate_coefficients",
    "affine_plan",
    "available_backends",
    "backend_capabilities",
    "canonicalize_colored_digraphs",
    "chebyshev_lobatto_endpoint_derivatives",
    "csr_common_neighbors",
    "decode_graph6",
    "delete_graph_vertices",
    "encode_graph6",
    "digest_u64_rows",
    "determinants_mod_u32",
    "dirichlet_inverse",
    "fused_two_level",
    "evaluate_taylor_basis",
    "enumerate_csr_triangles",
    "find_cliques",
    "find_independent_sets",
    "filon_chebyshev_inner_product",
    "graph_invariants",
    "hip_available",
    "hip_cnf_available",
    "hip_modular_available",
    "hip_modular_linear_available",
    "hip_subset_actions_available",
    "native_version",
    "oriented_square_cover_words",
    "oriented_square_weighted_scores",
    "pack_boolean_assignments",
    "pack_digraph_adjacency",
    "power_moments",
    "graph_pair_profiles",
    "induced_subgraph_profiles",
    "induced_subgraph_profile_stack",
    "rooted_leaf_attachment_features",
    "segmented_complex_stats",
    "serialize_u64_row",
    "sparse_block_coloops_mod_u32",
    "sparse_rank_mod_u32",
    "sparse_rank_mod_u32_batch",
    "taylor_coefficients",
    "truncated_inverse",
    "undirected_csr",
    "MestreApTables",
    "QuarticFibre",
    "mestre_ap_tables",
    "mestre_locus_residual",
    "mestre_quartic",
    "quartic_points",
    "union_closed_family_masks",
    "AdaptiveAreaBatch",
    "AdaptiveBackend",
    "ExactAdaptiveAreaBatch",
    "adaptive_areas",
    "exact_adaptive_areas",
    "quadratic_target_tables",
    "restriction_assignment",
    "restriction_code",
    "restriction_count",
    "CIBackend",
    "CanonicalCayleyBatch",
    "CayleyGraphBatch",
    "CoherentConfiguration",
    "DerivativeOrbitBatch",
    "DerivativeOrbitPartition",
    "DoubleCosetPartition",
    "FixedWeightSubsetOrbits",
    "GeneralizedDihedralGroup",
    "GroupBackend",
    "InverseClosedAtoms",
    "PermutationGroup",
    "SchreierSimsChain",
    "SubsetOrbitPartition",
    "WL2Refinement",
    "atom_subsets_to_element_words",
    "compose_u64_mask_luts",
    "canonicalize_cayley_graphs",
    "cayley_graphs",
    "coherent_configuration",
    "compose_permutations",
    "deduplicate_subset_orbits",
    "derivative_group_orbits",
    "derivative_orbit_partitions",
    "double_cosets",
    "enumerate_fixed_weight_subset_orbits",
    "enumerate_subset_orbits",
    "expand_atom_masks",
    "generalized_dihedral_automorphisms",
    "generalized_dihedral_group",
    "graph_coherent_configuration",
    "graph_wl2_refinement",
    "group_order",
    "induced_atom_action",
    "induced_atom_generators",
    "inverse_closed_atoms",
    "invert_permutation",
    "pack_subsets",
    "permutation_double_cosets",
    "u64_mask_lut",
    "permutation_group_contains",
    "permutation_orbits",
    "schreier_sims",
    "wl2_refinement",
]
